/**
 * Materia prima del catálogo de muestra: nombres, marcas y rangos de precio
 * verosímiles de un autoservicio de barrio.
 *
 * Está separado del seed porque son datos, no lógica. Los precios son rangos
 * en centavos y el seed sortea dentro del rango con semilla fija, así que dos
 * corridas dan exactamente el mismo catálogo.
 */

export interface PlantillaCategoria {
  nombre: string;
  color: string;
  unidad: 'unidad' | 'kg';
  /** Rango de precio de venta, en centavos. */
  precio: [number, number];
  /** Margen sobre el costo, en puntos porcentuales. */
  margen: [number, number];
  articulos: string[];
  marcas: string[];
  presentaciones: string[];
}

export const CATEGORIAS: PlantillaCategoria[] = [
  {
    nombre: 'Almacén',
    color: '#c9922f',
    unidad: 'unidad',
    precio: [55_000, 340_000],
    margen: [22, 35],
    articulos: [
      'Arroz largo fino',
      'Fideos guiseros',
      'Fideos tallarín',
      'Polenta',
      'Harina 000',
      'Harina 0000',
      'Azúcar',
      'Yerba mate',
      'Yerba compuesta',
      'Café molido',
      'Té en saquitos',
      'Aceite de girasol',
      'Aceite de oliva',
      'Vinagre de alcohol',
      'Sal fina',
      'Sal gruesa',
      'Puré de tomate',
      'Tomate triturado',
      'Arvejas en lata',
      'Choclo en lata',
      'Atún al natural',
      'Caballa en aceite',
      'Lentejas secas',
      'Porotos negros',
      'Garbanzos',
      'Mermelada de durazno',
      'Dulce de leche',
      'Miel',
      'Galletitas de agua',
      'Galletitas dulces',
      'Pan rallado',
      'Rebozador',
      'Caldo en cubos',
      'Sopa crema',
      'Mayonesa',
      'Ketchup',
      'Mostaza',
      'Salsa de soja',
    ],
    marcas: ['Marolio', 'Cañuelas', 'Molinos', 'Arcor', 'Knorr', 'Natura', 'Cocinero', 'Ilolay'],
    presentaciones: ['500 g', '1 kg', '900 ml', '400 g', '340 g', '250 g'],
  },
  {
    nombre: 'Bebidas',
    color: '#3d7fd6',
    unidad: 'unidad',
    precio: [70_000, 450_000],
    margen: [18, 30],
    articulos: [
      'Gaseosa cola',
      'Gaseosa lima limón',
      'Gaseosa naranja',
      'Agua sin gas',
      'Agua con gas',
      'Agua saborizada',
      'Jugo de naranja',
      'Jugo en polvo',
      'Cerveza rubia',
      'Cerveza negra',
      'Vino tinto',
      'Vino blanco',
      'Fernet',
      'Aperitivo',
      'Soda',
      'Isotónica',
      'Energizante',
      'Tónica',
    ],
    marcas: ['Coca-Cola', 'Manaos', 'Villa del Sur', 'Quilmes', 'Brahma', 'Cepita', 'Tang', 'Baggio'],
    presentaciones: ['500 ml', '1,5 L', '2,25 L', '2 L', '1 L', '355 ml', '750 ml'],
  },
  {
    nombre: 'Lácteos',
    color: '#e8e3d5',
    unidad: 'unidad',
    precio: [70_000, 300_000],
    margen: [16, 26],
    articulos: [
      'Leche entera',
      'Leche descremada',
      'Leche chocolatada',
      'Yogur bebible',
      'Yogur firme',
      'Queso crema',
      'Queso untable',
      'Manteca',
      'Crema de leche',
      'Ricota',
      'Postre de vainilla',
      'Flan',
      'Dulce de leche repostero',
      'Leche en polvo',
    ],
    marcas: ['La Serenísima', 'Sancor', 'Ilolay', 'Milkaut', 'Tregar', 'Verónica'],
    presentaciones: ['1 L', '200 g', '190 g', '300 g', '120 g', '500 g'],
  },
  {
    nombre: 'Fiambrería',
    color: '#c86a6a',
    unidad: 'kg',
    precio: [550_000, 1_400_000],
    margen: [28, 42],
    articulos: [
      'Jamón cocido',
      'Jamón crudo',
      'Salame milán',
      'Salamín tipo Colonia',
      'Mortadela',
      'Bondiola',
      'Panceta ahumada',
      'Queso cremoso',
      'Queso port salut',
      'Queso sardo',
      'Queso rallado',
      'Queso de máquina',
      'Muzzarella',
      'Provolone',
    ],
    marcas: ['Paladini', 'Cagnoli', 'La Piamontesa', 'Punta del Agua', 'Sancor'],
    presentaciones: ['por kg'],
  },
  {
    nombre: 'Verdulería',
    color: '#5aa860',
    unidad: 'kg',
    precio: [55_000, 280_000],
    margen: [35, 55],
    articulos: [
      'Papa negra',
      'Batata',
      'Cebolla',
      'Tomate perita',
      'Tomate redondo',
      'Zanahoria',
      'Zapallo anco',
      'Zapallito',
      'Morrón rojo',
      'Lechuga criolla',
      'Banana',
      'Manzana roja',
      'Naranja de jugo',
      'Mandarina',
      'Limón',
      'Pera',
      'Uva',
      'Frutilla',
    ],
    marcas: ['Mercado de Abasto'],
    presentaciones: ['por kg'],
  },
  {
    nombre: 'Carnicería',
    color: '#a8434f',
    unidad: 'kg',
    precio: [420_000, 1_100_000],
    margen: [20, 32],
    articulos: [
      'Carne picada común',
      'Carne picada especial',
      'Nalga',
      'Cuadrada',
      'Bola de lomo',
      'Asado de tira',
      'Vacío',
      'Matambre',
      'Pollo entero',
      'Pata muslo',
      'Pechuga',
      'Chorizo',
      'Morcilla',
      'Milanesa de carne',
    ],
    marcas: ['Del frigorífico'],
    presentaciones: ['por kg'],
  },
  {
    nombre: 'Panadería',
    color: '#d0a26a',
    unidad: 'unidad',
    precio: [40_000, 230_000],
    margen: [40, 60],
    articulos: [
      'Pan francés',
      'Pan de mesa',
      'Figazza',
      'Facturas surtidas',
      'Medialunas',
      'Bizcochos de grasa',
      'Pan lactal',
      'Pan de salvado',
      'Prepizza',
      'Tortitas negras',
    ],
    marcas: ['De la casa', 'Fargo', 'Bimbo', 'Lactal'],
    presentaciones: ['unidad', 'docena', '500 g', '620 g'],
  },
  {
    nombre: 'Limpieza',
    color: '#4fa8b8',
    unidad: 'unidad',
    precio: [60_000, 380_000],
    margen: [30, 45],
    articulos: [
      'Detergente',
      'Lavandina',
      'Jabón en polvo',
      'Jabón líquido para ropa',
      'Suavizante',
      'Limpiador de pisos',
      'Limpiavidrios',
      'Desengrasante',
      'Esponja',
      'Rejilla',
      'Bolsas de residuo',
      'Papel de cocina',
      'Insecticida',
      'Desodorante de ambiente',
    ],
    marcas: ['Magistral', 'Ayudín', 'Ala', 'Skip', 'Cif', 'Poett', 'Vim', 'Raid'],
    presentaciones: ['750 ml', '1 L', '3 L', '800 g', '450 ml', '30 unidades'],
  },
  {
    nombre: 'Perfumería',
    color: '#b07cc6',
    unidad: 'unidad',
    precio: [90_000, 520_000],
    margen: [32, 48],
    articulos: [
      'Shampoo',
      'Acondicionador',
      'Jabón de tocador',
      'Pasta dental',
      'Cepillo de dientes',
      'Desodorante en aerosol',
      'Desodorante roll on',
      'Papel higiénico',
      'Toallas femeninas',
      'Pañales',
      'Algodón',
      'Máquina de afeitar',
      'Crema de enjuague',
    ],
    marcas: ['Sedal', 'Pantene', 'Dove', 'Rexona', 'Colgate', 'Elvive', 'Higienol', 'Pampers'],
    presentaciones: ['400 ml', '200 ml', '90 g', '4 unidades', '8 unidades', '24 unidades'],
  },
  {
    nombre: 'Golosinas',
    color: '#e0685f',
    unidad: 'unidad',
    precio: [25_000, 190_000],
    margen: [35, 55],
    articulos: [
      'Alfajor simple',
      'Alfajor triple',
      'Chocolate con leche',
      'Chocolate blanco',
      'Turrón',
      'Caramelos masticables',
      'Chupetines',
      'Chicles',
      'Pastillas de menta',
      'Bombones',
      'Barra de cereal',
      'Papas fritas',
      'Palitos de maíz',
      'Maní salado',
      'Galletitas rellenas',
    ],
    marcas: ['Arcor', 'Bagley', 'Terrabusi', 'Milka', 'Águila', 'Mogul', 'Lays', 'Pehuamar'],
    presentaciones: ['unidad', '100 g', '55 g', '150 g', '3 unidades'],
  },
  {
    nombre: 'Congelados',
    color: '#6fa9d9',
    unidad: 'unidad',
    precio: [110_000, 600_000],
    margen: [25, 38],
    articulos: [
      'Hamburguesas',
      'Milanesas de soja',
      'Bastones de merluza',
      'Papas prefritas',
      'Verduras congeladas',
      'Nuggets de pollo',
      'Empanadas congeladas',
      'Helado',
      'Pizza congelada',
    ],
    marcas: ['Paty', 'Granja del Sol', 'McCain', 'Swift', 'Grido'],
    presentaciones: ['4 unidades', '6 unidades', '500 g', '1 kg', '300 g'],
  },
  {
    nombre: 'Bazar',
    color: '#8d8d8d',
    unidad: 'unidad',
    precio: [60_000, 600_000],
    margen: [45, 70],
    articulos: [
      'Encendedor',
      'Pilas AA',
      'Pilas AAA',
      'Lamparita LED',
      'Vela',
      'Fósforos',
      'Filtros de café',
      'Vasos descartables',
      'Servilletas',
      'Papel aluminio',
      'Film adherente',
      'Cinta adhesiva',
      'Cuaderno',
      'Birome',
    ],
    marcas: ['Duracell', 'Philips', 'Tramontina', 'Bic', 'Rayovac', 'Genérico'],
    presentaciones: ['unidad', '2 unidades', '4 unidades', '50 unidades', '30 m'],
  },
];

export const PROVEEDORES = [
  { nombre: 'Distribuidora Centro', telefono: '351 421-8890', cuit: '30-71234567-9' },
  { nombre: 'Mayorista Vélez', telefono: '351 456-2210', cuit: '30-69874521-4' },
  { nombre: 'Lácteos del Sur', telefono: '351 488-9012', cuit: '30-70112233-1' },
  { nombre: 'Frigorífico Alto Alberdi', telefono: '351 470-3344', cuit: '30-65432198-7' },
  { nombre: 'Mercado de Abasto Córdoba', telefono: '351 433-1120', cuit: '30-61234509-2' },
  { nombre: 'Química y Limpieza SRL', telefono: '351 499-7788', cuit: '30-71987654-3' },
];

export const CLIENTES = [
  'Rotisería La Esquina',
  'Kiosco Don Pedro',
  'Panadería San Cayetano',
  'Comedor Barrio Norte',
  'Almacén de Marta',
];
